const APPOINTMENT_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  RESCHEDULED: 'RESCHEDULED',
  NOT_SERVED: 'NOT_SERVED',
  CANCELLED: 'CANCELLED',
};

const USER_ROLES = {
  ADMIN: 'ADMIN',
  STAFF: 'STAFF',
};

const GENDER_OPTIONS = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
};

const APPOINTMENT_NUMBER_PREFIX = 'APP';

module.exports = {
  APPOINTMENT_STATUS,
  USER_ROLES,
  GENDER_OPTIONS,
  APPOINTMENT_NUMBER_PREFIX,
};